### ISSUE TITLE
Clicking link in table throws error in grid

### ISSUE THREAD

**Issue by Morgwee** [Morgwee/PWATracker#3]
Hi @vitoc,

Seems with the new addition, when you click a link in the grid, it tries to navigate by cannot connect.
![Screenshot 2021-08-04 131221](https://user-images.githubusercontent.com/48145541/128125616-7ce12af3-5239-4057-88b4-ba5421c51390.png)

**Comment by vitoc** [comment]
This is resolved with PR #4

**Comment by Morgwee** [comment]
Thanks Vito
